# Generated by Django 3.1.7 on 2021-04-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='locations',
            field=models.ManyToManyField(to='rest_api.Location'),
        ),
    ]
