# Generated by Django 3.1.7 on 2021-04-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_region_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='country',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='country',
            name='regions',
            field=models.ManyToManyField(to='rest_api.Region'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='region',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
