# Generated by Django 3.1.7 on 2021-04-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20210409_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtremeSport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=100)),
                ('daily_costs', models.CharField(max_length=15)),
                ('country', models.ManyToManyField(to='rest_api.Country')),
            ],
        ),
    ]
