# Generated by Django 3.1.7 on 2021-04-09 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0010_delete_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('regions', models.ManyToManyField(to='rest_api.Region')),
            ],
        ),
        migrations.CreateModel(
            name='ExtremeSport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=100)),
                ('daily_costs', models.CharField(max_length=15)),
                ('country', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='rest_api.country')),
            ],
        ),
    ]
