# Generated by Django 3.1.7 on 2021-04-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0012_auto_20210409_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extremesport',
            name='country',
        ),
        migrations.AddField(
            model_name='extremesport',
            name='country',
            field=models.ManyToManyField(to='rest_api.Country'),
        ),
    ]
