# Generated by Django 3.1.7 on 2021-04-15 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0017_auto_20210409_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extremesport',
            options={'ordering': ['-daily_costs']},
        ),
    ]
