# Generated by Django 3.1.7 on 2021-04-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0018_auto_20210415_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.CharField(default='euro', max_length=10),
        ),
        migrations.AddField(
            model_name='country',
            name='official_language',
            field=models.CharField(default='', max_length=100),
        ),
    ]
