# Generated by Django 3.1.7 on 2021-04-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0019_auto_20210415_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extremesport',
            name='place',
        ),
        migrations.AddField(
            model_name='location',
            name='sports',
            field=models.ManyToManyField(to='rest_api.ExtremeSport'),
        ),
    ]
