# Generated by Django 3.1.7 on 2021-04-15 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0021_auto_20210415_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.country'),
        ),
    ]
