# Generated by Django 3.1.7 on 2021-04-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0022_auto_20210415_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extremesport',
            name='period',
            field=models.DateTimeField(),
        ),
    ]
