# Generated by Django 3.1.7 on 2021-04-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0026_auto_20210415_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extremesport',
            name='period',
            field=models.DateField(),
        ),
    ]
