# Generated by Django 3.1.7 on 2021-04-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0029_extremesport_periods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extremesport',
            name='periods',
            field=models.DateField(),
        ),
    ]
