# Generated by Django 3.1.7 on 2021-04-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0030_auto_20210415_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extremesport',
            name='periods',
        ),
        migrations.AlterField(
            model_name='extremesport',
            name='period',
            field=models.DateField(),
        ),
    ]
