# Generated by Django 3.1.7 on 2021-04-15 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0031_auto_20210415_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='extremesport',
            name='periods',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extremesport',
            name='period',
            field=models.CharField(default='dasewda', max_length=100),
        ),
    ]
