# Generated by Django 3.1.7 on 2021-04-15 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0033_remove_extremesport_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extremesport',
            old_name='periods',
            new_name='end_of_season',
        ),
        migrations.AddField(
            model_name='extremesport',
            name='start_of_season',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
