# Generated by Django 3.1.7 on 2021-04-16 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0035_auto_20210415_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='regions',
        ),
        migrations.AddField(
            model_name='location',
            name='regions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest_api.region'),
        ),
    ]
