# Generated by Django 3.1.7 on 2021-04-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0036_auto_20210416_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extremesport',
            options={},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-daily_costs']},
        ),
        migrations.RemoveField(
            model_name='extremesport',
            name='daily_costs',
        ),
        migrations.AddField(
            model_name='location',
            name='daily_costs',
            field=models.CharField(default='', max_length=15),
        ),
    ]
